#!/bin/bash
#
# build
# A simple wrapper around antimony.

# IMPORTS
source /usr/local/bin/tputcolors

# VARIABLES
FONT_BUILD_DIR='font'

# =============================================================================
# {

echo "Building with antimony..."
antimony -f ttf,eot,woff,svg $FONT_BUILD_DIR/RedLabel-Regular.otf
success "Done."
echo

echo "Base64 encoding woff..."
galena -f font/RedLabel-Regular.woff sass/_red-label-core.scss
success "Done."
echo

# }
# =============================================================================
